package com.example.data.usecase

import com.example.data.local.MealDao
import com.example.data.local.MealEntity
import com.example.data.model.BioGlycemicImpact
import com.example.data.model.MealSlot
import com.example.data.util.AetherDateUtils
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import java.util.Locale
import java.util.UUID

/**
 * UseCase implementing fault-tolerant parsing of external diet plans generated by
 * ChatGPT, Claude, Gemini or copy-pasted text.
 */
class MealImportUseCase(
    private val mealDao: MealDao
) {
    suspend fun execute(rawTextOrJson: String): Result<Int> = withContext(Dispatchers.IO) {
        try {
            val clean = rawTextOrJson.trim()
            if (clean.isBlank()) {
                return@withContext Result.failure(IllegalArgumentException("Empty input text"))
            }

            val today = AetherDateUtils.getTodayIso()
            val importedMeals = mutableListOf<MealEntity>()

            // 1. Try Parsing as JSON Array or JSON Object
            if (clean.startsWith("[") || clean.startsWith("{")) {
                try {
                    if (clean.startsWith("[")) {
                        val jsonArray = JSONArray(clean)
                        for (i in 0 until jsonArray.length()) {
                            val obj = jsonArray.optJSONObject(i) ?: continue
                            val entity = parseMealJsonObject(obj, today)
                            if (entity != null) importedMeals.add(entity)
                        }
                    } else {
                        val jsonObject = JSONObject(clean)
                        if (jsonObject.has("meals")) {
                            val array = jsonObject.optJSONArray("meals")
                            if (array != null) {
                                for (i in 0 until array.length()) {
                                    val obj = array.optJSONObject(i) ?: continue
                                    val entity = parseMealJsonObject(obj, today)
                                    if (entity != null) importedMeals.add(entity)
                                }
                            }
                        } else {
                            val slots = listOf("breakfast", "lunch", "dinner", "snack", "desayuno", "almuerzo", "comida", "cena", "merienda")
                            for (key in slots) {
                                if (jsonObject.has(key)) {
                                    val obj = jsonObject.optJSONObject(key)
                                    if (obj != null) {
                                        val entity = parseMealJsonObject(obj, today, fallbackSlot = mapKeyToSlot(key))
                                        if (entity != null) importedMeals.add(entity)
                                    }
                                }
                            }
                        }
                    }
                } catch (e: Exception) {
                    // Fallback to text parsing if JSON parse failed
                }
            }

            // 2. If JSON parsing didn't produce meals, use Natural Language Line Parser
            if (importedMeals.isEmpty()) {
                val lines = clean.lines()
                var currentSlot: MealSlot = MealSlot.BREAKFAST
                var currentTitle = ""
                var currentDesc = ""
                val currentIngredients = mutableListOf<String>()
                var currentProtein = 0
                var currentCarbs = 0
                var currentFat = 0
                var currentKcal = 0

                fun commitCurrentMeal() {
                    if (currentTitle.isNotBlank()) {
                        val id = "meal-" + UUID.randomUUID().toString().take(8)
                        val kcal = if (currentKcal > 0) currentKcal else (currentProtein * 4 + currentCarbs * 4 + currentFat * 9)
                        importedMeals.add(
                            MealEntity(
                                id = id,
                                slot = currentSlot,
                                title = currentTitle.trim(),
                                description = currentDesc.ifBlank { "Comida importada desde IA externa" },
                                prepTimeMinutes = 15,
                                ingredients = if (currentIngredients.isNotEmpty()) currentIngredients.toList() else listOf(currentTitle),
                                usesBatchCookedBase = false,
                                allIngredientsInStock = true,
                                bioImpact = BioGlycemicImpact.MODERATE_STEADY,
                                isCompleted = false,
                                proteinGrams = currentProtein,
                                carbsGrams = currentCarbs,
                                fatGrams = currentFat,
                                caloriesKcal = kcal,
                                dateIso = today
                            )
                        )
                        currentTitle = ""
                        currentDesc = ""
                        currentIngredients.clear()
                        currentProtein = 0
                        currentCarbs = 0
                        currentFat = 0
                        currentKcal = 0
                    }
                }

                for (line in lines) {
                    val trimmed = line.trim().removePrefix("-").removePrefix("*").trim()
                    if (trimmed.isBlank()) continue

                    val lower = trimmed.lowercase(Locale.ROOT)
                    val detectedSlot = when {
                        lower.contains("desayuno") || lower.contains("breakfast") -> MealSlot.BREAKFAST
                        lower.contains("almuerzo") || lower.contains("comida") || lower.contains("lunch") -> MealSlot.LUNCH
                        lower.contains("cena") || lower.contains("dinner") -> MealSlot.DINNER
                        lower.contains("snack") || lower.contains("merienda") || lower.contains("tentempi") -> MealSlot.SNACK
                        else -> null
                    }

                    if (detectedSlot != null) {
                        commitCurrentMeal()
                        currentSlot = detectedSlot
                        val afterColon = if (trimmed.contains(":")) trimmed.substringAfter(":").trim() else ""
                        if (afterColon.isNotBlank()) {
                            currentTitle = extractTitleWithoutMacros(afterColon)
                            currentDesc = afterColon
                            extractMacrosFromText(afterColon).let { (p, c, f, k) ->
                                currentProtein = p
                                currentCarbs = c
                                currentFat = f
                                currentKcal = k
                            }
                        }
                    } else if (currentTitle.isBlank()) {
                        currentTitle = extractTitleWithoutMacros(trimmed)
                        currentDesc = trimmed
                        extractMacrosFromText(trimmed).let { (p, c, f, k) ->
                            currentProtein = p
                            currentCarbs = c
                            currentFat = f
                            currentKcal = k
                        }
                    } else {
                        val items = trimmed.split(",", ";", "•", "+").map { it.trim() }.filter { it.length > 2 }
                        currentIngredients.addAll(items)
                        extractMacrosFromText(trimmed).let { (p, c, f, k) ->
                            if (p > 0) currentProtein = p
                            if (c > 0) currentCarbs = c
                            if (f > 0) currentFat = f
                            if (k > 0) currentKcal = k
                        }
                    }
                }
                commitCurrentMeal()
            }

            if (importedMeals.isEmpty()) {
                return@withContext Result.failure(IllegalArgumentException("No valid meals could be detected in the provided text."))
            }

            mealDao.insertMeals(importedMeals)
            Result.success(importedMeals.size)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    private fun mapKeyToSlot(key: String): MealSlot {
        val lower = key.lowercase(Locale.ROOT)
        return when {
            lower.contains("break") || lower.contains("desay") -> MealSlot.BREAKFAST
            lower.contains("lunch") || lower.contains("almu") || lower.contains("comida") -> MealSlot.LUNCH
            lower.contains("din") || lower.contains("cena") -> MealSlot.DINNER
            else -> MealSlot.SNACK
        }
    }

    private fun parseMealJsonObject(obj: JSONObject, today: String, fallbackSlot: MealSlot = MealSlot.BREAKFAST): MealEntity? {
        val title = obj.optString("title").ifBlank { obj.optString("name") }
        if (title.isBlank()) return null

        val slotStr = obj.optString("slot").ifBlank { fallbackSlot.name }
        val slot = try {
            MealSlot.valueOf(slotStr.uppercase(Locale.ROOT))
        } catch (e: Exception) {
            fallbackSlot
        }

        val desc = obj.optString("description").ifBlank { obj.optString("notes", "Comida importada de IA") }
        val prepTime = obj.optInt("prepTimeMinutes", obj.optInt("prep_time", 15))
        val p = obj.optInt("proteinGrams", obj.optInt("protein", 0))
        val c = obj.optInt("carbsGrams", obj.optInt("carbs", 0))
        val f = obj.optInt("fatGrams", obj.optInt("fat", 0))
        val kcal = obj.optInt("caloriesKcal", obj.optInt("calories", (p * 4 + c * 4 + f * 9)))

        val ingredientsList = mutableListOf<String>()
        val ingArray = obj.optJSONArray("ingredients")
        if (ingArray != null) {
            for (j in 0 until ingArray.length()) {
                val ing = ingArray.optString(j)
                if (ing.isNotBlank()) ingredientsList.add(ing)
            }
        }

        val id = "meal-" + UUID.randomUUID().toString().take(8)
        return MealEntity(
            id = id,
            slot = slot,
            title = title,
            description = desc,
            prepTimeMinutes = prepTime,
            ingredients = if (ingredientsList.isNotEmpty()) ingredientsList else listOf(title),
            usesBatchCookedBase = obj.optBoolean("usesBatchCookedBase", false),
            allIngredientsInStock = true,
            bioImpact = BioGlycemicImpact.MODERATE_STEADY,
            isCompleted = false,
            customSlotName = if (obj.has("customSlotName") && !obj.isNull("customSlotName")) obj.optString("customSlotName") else null,
            proteinGrams = p,
            carbsGrams = c,
            fatGrams = f,
            caloriesKcal = kcal,
            dateIso = today
        )
    }

    private fun extractTitleWithoutMacros(text: String): String {
        return text.replace(Regex("\\(.*\\)"), "")
            .replace(Regex("\\[.*\\]"), "")
            .replace(Regex("\\|.*"), "")
            .trim()
    }

    private fun extractMacrosFromText(text: String): Quadruple<Int, Int, Int, Int> {
        var protein = 0
        var carbs = 0
        var fat = 0
        var kcal = 0

        val pMatch = Regex("(\\d+)\\s*(?:g|gr|gramos)?\\s*(?:de\\s*)?(?:prote[ií]na|protein|prot|p\\b)", RegexOption.IGNORE_CASE).find(text)
        if (pMatch != null) protein = pMatch.groupValues[1].toIntOrNull() ?: 0

        val cMatch = Regex("(\\d+)\\s*(?:g|gr|gramos)?\\s*(?:de\\s*)?(?:carbos|carbohidratos|carbs|hc|c\\b)", RegexOption.IGNORE_CASE).find(text)
        if (cMatch != null) carbs = cMatch.groupValues[1].toIntOrNull() ?: 0

        val fMatch = Regex("(\\d+)\\s*(?:g|gr|gramos)?\\s*(?:de\\s*)?(?:grasas|grasa|fat|g\\b)", RegexOption.IGNORE_CASE).find(text)
        if (fMatch != null) fat = fMatch.groupValues[1].toIntOrNull() ?: 0

        val kMatch = Regex("(\\d+)\\s*(?:kcal|calor[ií]as|calories|cal\\b)", RegexOption.IGNORE_CASE).find(text)
        if (kMatch != null) kcal = kMatch.groupValues[1].toIntOrNull() ?: 0

        return Quadruple(protein, carbs, fat, kcal)
    }

    private data class Quadruple<A, B, C, D>(val first: A, val second: B, val third: C, val fourth: D)
}
