package com.example.data.local

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.TypeConverters
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase
import com.example.data.model.*
import com.example.ui.i18n.AppLanguage
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import java.time.LocalDate

@Database(
    entities = [
        TaskEntity::class,
        TimeBlockEntity::class,
        PantryEntity::class,
        MealEntity::class,
        HabitEntity::class,
        BiometricEntity::class,
        CompletionLogEntity::class,
        DailySummaryEntity::class,
        AiMessageEntity::class,
        QuickNoteEntity::class,
        FocusSessionEntity::class
    ],
    version = 13,
    exportSchema = false
)
@TypeConverters(Converters::class)
abstract class AetherDatabase : RoomDatabase() {
    abstract fun taskDao(): TaskDao
    abstract fun timeBlockDao(): TimeBlockDao
    abstract fun pantryDao(): PantryDao
    abstract fun mealDao(): MealDao
    abstract fun habitDao(): HabitDao
    abstract fun biometricDao(): BiometricDao
    abstract fun completionLogDao(): CompletionLogDao
    abstract fun dailySummaryDao(): DailySummaryDao
    abstract fun aiMessageDao(): AiMessageDao
    abstract fun quickNoteDao(): QuickNoteDao
    abstract fun focusSessionDao(): FocusSessionDao

    companion object {
        @Volatile
        private var INSTANCE: AetherDatabase? = null

        /**
         * Migration from Database v1 to v2:
         * Recreates the `biometrics` table with an autogenerated integer primary key `id`
         * and a unique index on `date` to prevent duplicate daily collisions.
         */
        val MIGRATION_1_2 = object : Migration(1, 2) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("DROP TABLE IF EXISTS biometrics_old")
                db.execSQL("ALTER TABLE biometrics RENAME TO biometrics_old")
                db.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `biometrics` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `date` TEXT NOT NULL,
                        `readinessScore` INTEGER NOT NULL,
                        `perceivedEnergy` INTEGER NOT NULL,
                        `sleepHours` REAL NOT NULL,
                        `sleepQuality` INTEGER NOT NULL,
                        `chronotype` TEXT NOT NULL,
                        `recoveryModeTriggered` INTEGER NOT NULL,
                        `graceDayActive` INTEGER NOT NULL
                    )
                    """.trimIndent()
                )
                db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS `index_biometrics_date` ON `biometrics` (`date`)")
                db.execSQL(
                    """
                    INSERT OR REPLACE INTO `biometrics` (
                        `date`, `readinessScore`, `perceivedEnergy`, `sleepHours`, `sleepQuality`, `chronotype`, `recoveryModeTriggered`, `graceDayActive`
                    )
                    SELECT `date`, `readinessScore`, `perceivedEnergy`, `sleepHours`, `sleepQuality`, `chronotype`, `recoveryModeTriggered`, `graceDayActive`
                    FROM `biometrics_old`
                    """.trimIndent()
                )
                db.execSQL("DROP TABLE IF EXISTS biometrics_old")
            }
        }

        /**
         * Non-destructive Migration from Database v2 to v3:
         * Creates `completion_logs` and `daily_summaries` tables for persistent multi-year history.
         */
        val MIGRATION_2_3 = object : Migration(2, 3) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `completion_logs` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `dateIso` TEXT NOT NULL,
                        `itemType` TEXT NOT NULL,
                        `itemId` TEXT NOT NULL,
                        `title` TEXT NOT NULL,
                        `status` TEXT NOT NULL,
                        `timestamp` INTEGER NOT NULL
                    )
                    """.trimIndent()
                )
                db.execSQL("CREATE INDEX IF NOT EXISTS `index_completion_logs_dateIso` ON `completion_logs` (`dateIso`)")
                db.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `daily_summaries` (
                        `dateIso` TEXT PRIMARY KEY NOT NULL,
                        `totalCount` INTEGER NOT NULL,
                        `completedCount` INTEGER NOT NULL,
                        `partialCount` INTEGER NOT NULL,
                        `ratio` REAL NOT NULL
                    )
                    """.trimIndent()
                )
            }
        }

        /**
         * Non-destructive Migration from Database v3 to v4:
         * Adds customSlotName, macros (proteinGrams, carbsGrams, fatGrams, caloriesKcal),
         * and dateIso to `meals` table for Phase 3 Module 3 (Nutrición Moldeable).
         */
        val MIGRATION_3_4 = object : Migration(3, 4) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE `meals` ADD COLUMN `customSlotName` TEXT DEFAULT NULL")
                db.execSQL("ALTER TABLE `meals` ADD COLUMN `proteinGrams` INTEGER NOT NULL DEFAULT 0")
                db.execSQL("ALTER TABLE `meals` ADD COLUMN `carbsGrams` INTEGER NOT NULL DEFAULT 0")
                db.execSQL("ALTER TABLE `meals` ADD COLUMN `fatGrams` INTEGER NOT NULL DEFAULT 0")
                db.execSQL("ALTER TABLE `meals` ADD COLUMN `caloriesKcal` INTEGER NOT NULL DEFAULT 0")
                db.execSQL("ALTER TABLE `meals` ADD COLUMN `dateIso` TEXT NOT NULL DEFAULT ''")
            }
        }

        /**
         * Non-destructive Migration from Database v4 to v5:
         * Adds `ai_messages` table for Phase 3 Module 5 (Núcleo IA Mejorado / Chat & Favorite Notes).
         */
        val MIGRATION_4_5 = object : Migration(4, 5) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `ai_messages` (
                        `id` TEXT PRIMARY KEY NOT NULL,
                        `role` TEXT NOT NULL,
                        `content` TEXT NOT NULL,
                        `timestamp` INTEGER NOT NULL,
                        `isFavorite` INTEGER NOT NULL DEFAULT 0
                    )
                    """.trimIndent()
                )
                db.execSQL("CREATE INDEX IF NOT EXISTS `index_ai_messages_timestamp` ON `ai_messages` (`timestamp`)")
                db.execSQL("CREATE INDEX IF NOT EXISTS `index_ai_messages_isFavorite` ON `ai_messages` (`isFavorite`)")
            }
        }

        /**
         * Non-destructive Migration from Database v5 to v6:
         * Adds multi-variable bioenergetic metrics, dynamic cognitive ceiling fields,
         * and sleep/stress/motivation metrics to `biometrics` table.
         */
        val MIGRATION_5_6 = object : Migration(5, 6) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE `biometrics` ADD COLUMN `computedReadinessScore` INTEGER NOT NULL DEFAULT 75")
                db.execSQL("ALTER TABLE `biometrics` ADD COLUMN `sleepStartTime` TEXT NOT NULL DEFAULT '23:00'")
                db.execSQL("ALTER TABLE `biometrics` ADD COLUMN `sleepEndTime` TEXT NOT NULL DEFAULT '07:30'")
                db.execSQL("ALTER TABLE `biometrics` ADD COLUMN `sleepInterruptionsCount` INTEGER NOT NULL DEFAULT 0")
                db.execSQL("ALTER TABLE `biometrics` ADD COLUMN `wakeUpFeeling` TEXT NOT NULL DEFAULT 'RESTED'")
                db.execSQL("ALTER TABLE `biometrics` ADD COLUMN `currentEnergyLevel` INTEGER NOT NULL DEFAULT 7")
                db.execSQL("ALTER TABLE `biometrics` ADD COLUMN `stressLevel` INTEGER NOT NULL DEFAULT 3")
                db.execSQL("ALTER TABLE `biometrics` ADD COLUMN `motivationLevel` INTEGER NOT NULL DEFAULT 7")
                db.execSQL("ALTER TABLE `biometrics` ADD COLUMN `caffeineIntake` TEXT NOT NULL DEFAULT 'MODERATE'")
                db.execSQL("ALTER TABLE `biometrics` ADD COLUMN `exerciseDone` INTEGER NOT NULL DEFAULT 0")
                db.execSQL("ALTER TABLE `biometrics` ADD COLUMN `mealRegularity` TEXT NOT NULL DEFAULT 'REGULAR'")
                db.execSQL("ALTER TABLE `biometrics` ADD COLUMN `mentalOverload` INTEGER NOT NULL DEFAULT 0")
                db.execSQL("ALTER TABLE `biometrics` ADD COLUMN `emotionalConcern` TEXT NOT NULL DEFAULT ''")
                db.execSQL("ALTER TABLE `biometrics` ADD COLUMN `dynamicCognitiveCeilingMinutes` INTEGER NOT NULL DEFAULT 180")
                db.execSQL("ALTER TABLE `biometrics` ADD COLUMN `cognitiveCeilingReason` TEXT NOT NULL DEFAULT 'Línea base estándar ajustada por biometría.'")
            }
        }

        /**
         * Non-destructive Migration from Database v6 to v7:
         * Adds maxGraceDaysPerPeriod, graceDayLastUsedDate, lastCompletedDate to `habits` table.
         * Adds isArchived, completedDate to `tasks` table.
         */
        val MIGRATION_6_7 = object : Migration(6, 7) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE `habits` ADD COLUMN `maxGraceDaysPerPeriod` INTEGER NOT NULL DEFAULT 2")
                db.execSQL("ALTER TABLE `habits` ADD COLUMN `graceDayLastUsedDate` TEXT NOT NULL DEFAULT ''")
                db.execSQL("ALTER TABLE `habits` ADD COLUMN `lastCompletedDate` TEXT NOT NULL DEFAULT ''")
                db.execSQL("ALTER TABLE `tasks` ADD COLUMN `isArchived` INTEGER NOT NULL DEFAULT 0")
                db.execSQL("ALTER TABLE `tasks` ADD COLUMN `completedDate` TEXT NOT NULL DEFAULT ''")
            }
        }

        /**
         * Non-destructive Migration from Database v7 to v8:
         * Creates `quick_notes` and `focus_sessions` tables.
         */
        val MIGRATION_7_8 = object : Migration(7, 8) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `quick_notes` (
                        `id` TEXT PRIMARY KEY NOT NULL,
                        `content` TEXT NOT NULL,
                        `createdAt` INTEGER NOT NULL,
                        `isProcessed` INTEGER NOT NULL DEFAULT 0,
                        `convertedToTaskId` TEXT DEFAULT NULL
                    )
                    """.trimIndent()
                )
                db.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `focus_sessions` (
                        `id` TEXT PRIMARY KEY NOT NULL,
                        `taskTitle` TEXT NOT NULL,
                        `durationMinutes` INTEGER NOT NULL,
                        `timestamp` INTEGER NOT NULL,
                        `isCompleted` INTEGER NOT NULL DEFAULT 1,
                        `linkedTaskId` TEXT DEFAULT NULL,
                        `roundNumber` INTEGER NOT NULL DEFAULT 1
                    )
                    """.trimIndent()
                )
                db.execSQL("CREATE INDEX IF NOT EXISTS `index_focus_sessions_timestamp` ON `focus_sessions` (`timestamp`)")
            }
        }

        /**
         * Non-destructive Migration from Database v8 to v9:
         * Adds isPermanent to `tasks` table for persistent/recurring tasks vs ephemeral tasks.
         */
        val MIGRATION_8_9 = object : Migration(8, 9) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE `tasks` ADD COLUMN `isPermanent` INTEGER NOT NULL DEFAULT 0")
            }
        }

        /**
         * Non-destructive Migration from Database v9 to v10:
         * Adds pendingStreakBeforeReset to `habits` table to preserve pre-rollover streak
         * for retroactive morning check-in confirmation.
         */
        val MIGRATION_9_10 = object : Migration(9, 10) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE `habits` ADD COLUMN `pendingStreakBeforeReset` INTEGER NOT NULL DEFAULT 0")
            }
        }

        /**
         * Non-destructive Migration from Database v10 to v11:
         * One-time data repair for the "phantom grace days" bug. Before this fix, the weekly
         * Grace Day counter only reset when the app happened to be opened ON a Monday
         * (checking `today.dayOfWeek == MONDAY`) instead of checking whether a Monday had
         * occurred at all since the last time the app was used. Any user who skipped opening
         * the app across a Monday kept a stale, non-zero `graceDaysUsed` carried over from a
         * previous week — even though they never actually used a Grace Day in the new week.
         * The rollover logic itself is already fixed (see AetherDateUtils.hasMondayBetween),
         * but that fix only affects the calculation going forward: it cannot retroactively
         * correct values already sitting in the database from before the fix existed. This
         * migration clears that stale count once so every habit starts the new logic clean.
         */
        val MIGRATION_10_11 = object : Migration(10, 11) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("UPDATE `habits` SET `graceDaysUsed` = 0")
            }
        }

        /**
         * Non-destructive Migration from Database v11 to v12:
         * Adds the indices that day-scoped queries actually rely on. Every meal query now
         * filters by dateIso, and completion logs are frequently looked up by itemId (per-item
         * history, duplicate-log checks during rollover). Without these, both were full table
         * scans that get progressively slower as history accumulates.
         */
        val MIGRATION_11_12 = object : Migration(11, 12) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("CREATE INDEX IF NOT EXISTS `index_meals_dateIso` ON `meals` (`dateIso`)")
                db.execSQL("CREATE INDEX IF NOT EXISTS `index_completion_logs_itemId` ON `completion_logs` (`itemId`)")
            }
        }

        /**
         * Non-destructive Migration from Database v12 to v13:
         * Adds bestStreakDays so a personal best survives a broken streak. Existing rows are
         * backfilled from whatever streak they currently hold (and from pendingStreakBeforeReset
         * if a reset is mid-flight), so users don't start at zero having already earned a streak.
         */
        val MIGRATION_12_13 = object : Migration(12, 13) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE `habits` ADD COLUMN `bestStreakDays` INTEGER NOT NULL DEFAULT 0")
                db.execSQL(
                    "UPDATE `habits` SET `bestStreakDays` = MAX(`streakDays`, `pendingStreakBeforeReset`)"
                )
            }
        }

        fun getDatabase(context: Context): AetherDatabase {
            return INSTANCE ?: synchronized(this) {
                val instance = Room.databaseBuilder(
                    context.applicationContext,
                    AetherDatabase::class.java,
                    "aether_os_database"
                )
                .addMigrations(MIGRATION_1_2, MIGRATION_2_3, MIGRATION_3_4, MIGRATION_4_5, MIGRATION_5_6, MIGRATION_6_7, MIGRATION_7_8, MIGRATION_8_9, MIGRATION_9_10, MIGRATION_10_11, MIGRATION_11_12, MIGRATION_12_13)
                .fallbackToDestructiveMigrationOnDowngrade() // Safe fallback on downgrade only
                // NOTE: no blanket fallbackToDestructiveMigration() here on purpose.
                // Every schema version bump must ship an explicit Migration, or real user
                // data would be silently wiped on update instead of failing loudly in testing.
                .addCallback(object : Callback() {
                    override fun onCreate(db: SupportSQLiteDatabase) {
                        super.onCreate(db)
                        // PRODUCTION: first-ever launch must start empty (Clean Slate),
                        // never with invented demo tasks/meals/history.
                        // Demo data is only ever loaded on-demand from Settings via loadDemoData().
                        CoroutineScope(Dispatchers.IO).launch {
                            val dbInstance = getDatabase(context.applicationContext)
                            populateCleanSlate(dbInstance, AppLanguage.SPANISH)
                        }
                    }
                })
                .build()
                INSTANCE = instance
                instance
            }
        }

        suspend fun clearAllAetherData(database: AetherDatabase, clearHistory: Boolean = false) {
            val taskDao = database.taskDao()
            val timeBlockDao = database.timeBlockDao()
            val pantryDao = database.pantryDao()
            val mealDao = database.mealDao()
            val habitDao = database.habitDao()
            val biometricDao = database.biometricDao()

            taskDao.clearAllTasks()
            timeBlockDao.clearAllTimeBlocks()
            pantryDao.clearAllPantry()
            mealDao.clearAllMeals()
            habitDao.clearAllHabits()
            biometricDao.clearAllBiometrics()

            if (clearHistory) {
                database.completionLogDao().clearAllLogs()
                database.dailySummaryDao().clearAllSummaries()
            }
        }

        /**
         * Clean Slate Initializer:
         * Starts the app in production with empty task, time block, pantry, and meal lists.
         * Only provisions the 5 Universal Anchor Habits (with streak 0 and grace 0)
         * and the current day's biometric baseline.
         * Note: History is NEVER cleared unless wipeHistory is explicitly true.
         */
        suspend fun populateCleanSlate(
            database: AetherDatabase,
            language: AppLanguage = AppLanguage.SPANISH,
            wipeHistory: Boolean = false
        ) {
            val taskDao = database.taskDao()
            val timeBlockDao = database.timeBlockDao()
            val pantryDao = database.pantryDao()
            val mealDao = database.mealDao()
            val habitDao = database.habitDao()
            val biometricDao = database.biometricDao()

            // 1. Wipe user-generated daily tables
            taskDao.clearAllTasks()
            timeBlockDao.clearAllTimeBlocks()
            pantryDao.clearAllPantry()
            mealDao.clearAllMeals()
            habitDao.clearAllHabits()

            // 2. Wipe history ONLY if explicitly requested
            if (wipeHistory) {
                database.completionLogDao().clearAllLogs()
                database.dailySummaryDao().clearAllSummaries()
            }

            // 2. Insert baseline Biometrics for Today's Date
            val today = LocalDate.now().toString()
            biometricDao.insertBiometric(
                BiometricEntity(
                    date = today,
                    readinessScore = 75,
                    perceivedEnergy = 75,
                    sleepHours = 7.5,
                    sleepQuality = 4,
                    chronotype = Chronotype.BEAR,
                    recoveryModeTriggered = false,
                    graceDayActive = false
                )
            )

            // 3. Insert the 5 Universal Anchor Habits (0 streak, 0 grace days used)
            val universalHabits = if (language == AppLanguage.SPANISH) {
                listOf(
                    HabitEntity(
                        id = "habit-1",
                        title = "Luz Solar Matutina (Anclaje Fotónico)",
                        description = "10-15 minutos de luz exterior directa para sincronizar el núcleo supraquiasmático.",
                        anchor = CircadianAnchor.MORNING_LIGHT,
                        isCompleted = false,
                        streakDays = 0,
                        graceDaysUsed = 0,
                        reframingTip = "Fallar un día es humano; regresar hoy es tu línea base."
                    ),
                    HabitEntity(
                        id = "habit-2",
                        title = "500ml Agua con Electrolitos Minerales",
                        description = "Rehidratar el tejido cerebral inmediatamente al despertar.",
                        anchor = CircadianAnchor.HYDRATION_ELECTROLYTES,
                        isCompleted = false,
                        streakDays = 0,
                        graceDaysUsed = 0,
                        reframingTip = "La hidratación celular prepara la función ejecutiva."
                    ),
                    HabitEntity(
                        id = "habit-3",
                        title = "Corte de Cafeína a las 14:00",
                        description = "Permite que la adenosina se aclare y protege la fase de sueño profundo.",
                        anchor = CircadianAnchor.CAFFEINE_CUTOFF,
                        isCompleted = false,
                        streakDays = 0,
                        graceDaysUsed = 0,
                        reframingTip = "Protege tu arquitectura de sueño sin culpa."
                    ),
                    HabitEntity(
                        id = "habit-4",
                        title = "Caminata de Descompresión Zona 2",
                        description = "20 min de movimiento suave para aclarar lactato y reiniciar foco.",
                        anchor = CircadianAnchor.ZONE_2_MOVEMENT,
                        isCompleted = false,
                        streakDays = 0,
                        graceDaysUsed = 0,
                        reframingTip = "El movimiento ligero calma el sistema nervioso simpático."
                    ),
                    HabitEntity(
                        id = "habit-5",
                        title = "Digital Sunset (Pantallas fuera a las 22:00)",
                        description = "Reducción de fotones azules para estimular melatonina natural.",
                        anchor = CircadianAnchor.DIGITAL_SUNSET,
                        isCompleted = false,
                        streakDays = 0,
                        graceDaysUsed = 0,
                        reframingTip = "La noche pertenece a la regeneración biológica."
                    )
                )
            } else {
                listOf(
                    HabitEntity(
                        id = "habit-1",
                        title = "Morning Sunlight Photonic Anchor",
                        description = "10-15 minutes direct outdoor light to reset master circadian clock (SCN).",
                        anchor = CircadianAnchor.MORNING_LIGHT,
                        isCompleted = false,
                        streakDays = 0,
                        graceDaysUsed = 0,
                        reframingTip = "Missing once is human; returning today is your baseline."
                    ),
                    HabitEntity(
                        id = "habit-2",
                        title = "500ml Water + Mineral Electrolytes",
                        description = "Rehydrate neural tissue immediately upon waking.",
                        anchor = CircadianAnchor.HYDRATION_ELECTROLYTES,
                        isCompleted = false,
                        streakDays = 0,
                        graceDaysUsed = 0,
                        reframingTip = "Cellular hydration primes executive function."
                    ),
                    HabitEntity(
                        id = "habit-3",
                        title = "Caffeine Stop at 14:00",
                        description = "Allows adenosine clearance to safeguard Stage 3 Deep Sleep.",
                        anchor = CircadianAnchor.CAFFEINE_CUTOFF,
                        isCompleted = false,
                        streakDays = 0,
                        graceDaysUsed = 0,
                        reframingTip = "Protect your sleep architecture without guilt."
                    ),
                    HabitEntity(
                        id = "habit-4",
                        title = "Zone 2 Decompression Stroll",
                        description = "20 mins low intensity movement for lactate clearance and reset.",
                        anchor = CircadianAnchor.ZONE_2_MOVEMENT,
                        isCompleted = false,
                        streakDays = 0,
                        graceDaysUsed = 0,
                        reframingTip = "Light movement calms the sympathetic nervous system."
                    ),
                    HabitEntity(
                        id = "habit-5",
                        title = "Digital Sunset (Screens Dark at 22:00)",
                        description = "Suppress blue photons to stimulate natural melatonin synthesis.",
                        anchor = CircadianAnchor.DIGITAL_SUNSET,
                        isCompleted = false,
                        streakDays = 0,
                        graceDaysUsed = 0,
                        reframingTip = "The night belongs to biological rejuvenation."
                    )
                )
            }
            habitDao.insertHabits(universalHabits)
        }

        /**
         * Demo Data Population (Invoked only on demand from Settings):
         */
        suspend fun populateInitialAetherData(database: AetherDatabase, language: AppLanguage = AppLanguage.SPANISH) {
            val taskDao = database.taskDao()
            val timeBlockDao = database.timeBlockDao()
            val pantryDao = database.pantryDao()
            val mealDao = database.mealDao()
            val habitDao = database.habitDao()
            val biometricDao = database.biometricDao()

            val today = LocalDate.now().toString()
            biometricDao.insertBiometric(
                BiometricEntity(
                    date = today,
                    readinessScore = 78,
                    perceivedEnergy = 80,
                    sleepHours = 7.8,
                    sleepQuality = 4,
                    chronotype = Chronotype.BEAR,
                    recoveryModeTriggered = false,
                    graceDayActive = false
                )
            )

            if (language == AppLanguage.SPANISH) {
                val spanishTasks = listOf(
                    TaskEntity(
                        id = "task-frog-1",
                        title = "Arquitectura del Motor Central y Despacho Aether",
                        description = "Diseñar máquina de estados y pruebas de límites para el módulo central bioenergético.",
                        energyLevel = EnergyLevel.HIGH,
                        priorityType = PriorityType.FROG,
                        estimatedMinutes = 90,
                        isCompleted = false,
                        isFrog = true,
                        scheduledTime = "09:30",
                        category = "Trabajo Profundo"
                    ),
                    TaskEntity(
                        id = "task-med-1",
                        title = "Revisar Bioanalíticas Semanales y Tendencias de Sueño",
                        description = "Analizar curvas de recuperación de pulso cardíaco y ajustar ventana de cafeína.",
                        energyLevel = EnergyLevel.MEDIUM,
                        priorityType = PriorityType.MEDIUM,
                        estimatedMinutes = 30,
                        isCompleted = false,
                        isFrog = false,
                        scheduledTime = "14:30",
                        category = "Biometría"
                    ),
                    TaskEntity(
                        id = "task-med-2",
                        title = "Batch Cooking: Base de Quinoa y Boniato para 3 Días",
                        description = "Ejecutar protocolo de cocción en lote para anular la fatiga de decisión en el almuerzo.",
                        energyLevel = EnergyLevel.MEDIUM,
                        priorityType = PriorityType.MEDIUM,
                        estimatedMinutes = 45,
                        isCompleted = true,
                        isFrog = false,
                        scheduledTime = "17:30",
                        category = "Nutrición"
                    ),
                    TaskEntity(
                        id = "task-med-3",
                        title = "Sintetizar Estudio de Cambios de Fase Circadiana",
                        description = "Redactar memorando conciso sobre tiempos de exposición a luxes para cronotipo lobo.",
                        energyLevel = EnergyLevel.MEDIUM,
                        priorityType = PriorityType.MEDIUM,
                        estimatedMinutes = 40,
                        isCompleted = false,
                        isFrog = false,
                        scheduledTime = "11:30",
                        category = "Trabajo Profundo"
                    ),
                    TaskEntity(
                        id = "task-quick-1",
                        title = "Limpiar bandeja de entrada a Cero (Inbox Zero)",
                        description = "Procesamiento por lotes en 10 minutos.",
                        energyLevel = EnergyLevel.LOW,
                        priorityType = PriorityType.QUICK,
                        estimatedMinutes = 15,
                        isCompleted = false,
                        isFrog = false,
                        category = "Administración"
                    ),
                    TaskEntity(
                        id = "task-quick-2",
                        title = "Reponer Aceite de Oliva Virgen Extra Ecológico",
                        description = "Añadir a la lista de despensa inteligente.",
                        energyLevel = EnergyLevel.LOW,
                        priorityType = PriorityType.QUICK,
                        estimatedMinutes = 5,
                        isCompleted = true,
                        isFrog = false,
                        category = "Logística"
                    ),
                    TaskEntity(
                        id = "task-quick-3",
                        title = "Regar el jardín de hierbas aromáticas",
                        description = "Micro-pausa sensorial y desconexión visual.",
                        energyLevel = EnergyLevel.LOW,
                        priorityType = PriorityType.QUICK,
                        estimatedMinutes = 10,
                        isCompleted = false,
                        isFrog = false,
                        category = "Hábito"
                    ),
                    TaskEntity(
                        id = "task-quick-4",
                        title = "Confirmar horario de retrospectiva del equipo",
                        description = "Mensaje asíncrono rápido.",
                        energyLevel = EnergyLevel.LOW,
                        priorityType = PriorityType.QUICK,
                        estimatedMinutes = 5,
                        isCompleted = false,
                        isFrog = false,
                        category = "Administración"
                    ),
                    TaskEntity(
                        id = "task-quick-5",
                        title = "Verificar nivel de batería de equipos de respaldo",
                        description = "Chequeo de mantenimiento preventivo.",
                        energyLevel = EnergyLevel.LOW,
                        priorityType = PriorityType.QUICK,
                        estimatedMinutes = 5,
                        isCompleted = false,
                        isFrog = false,
                        category = "Logística"
                    )
                )
                taskDao.insertTasks(spanishTasks)

                val spanishBlocks = listOf(
                    TimeBlockEntity(
                        id = "block-1",
                        startTime = "07:00",
                        endTime = "08:00",
                        blockType = BlockType.HABIT_ANCHOR,
                        title = "Ancla Fotónica & Recarga de Hidratación con Electrolitos",
                        isCompleted = true,
                        sortOrder = 1
                    ),
                    TimeBlockEntity(
                        id = "block-2",
                        startTime = "08:00",
                        endTime = "08:45",
                        blockType = BlockType.MEAL,
                        title = "Desayuno de Bajo Impacto Glucémico (Combustible Estable)",
                        isCompleted = true,
                        sortOrder = 2
                    ),
                    TimeBlockEntity(
                        id = "block-3",
                        startTime = "09:00",
                        endTime = "10:45",
                        blockType = BlockType.DEEP_WORK,
                        title = "🔥 ENFOQUE FROG: Arquitectura del Motor Central",
                        isCompleted = false,
                        linkedTaskId = "task-frog-1",
                        sortOrder = 3
                    ),
                    TimeBlockEntity(
                        id = "block-4",
                        startTime = "10:45",
                        endTime = "11:15",
                        blockType = BlockType.COGNITIVE_RECOVERY_BUFFER,
                        title = "Descanso Ocular Activo & Caminata Zona 1",
                        isCompleted = false,
                        sortOrder = 4
                    ),
                    TimeBlockEntity(
                        id = "block-5",
                        startTime = "11:15",
                        endTime = "12:15",
                        blockType = BlockType.DEEP_WORK,
                        title = "Síntesis de Cambios de Fase & Notas Técnicas",
                        isCompleted = false,
                        linkedTaskId = "task-med-3",
                        sortOrder = 5
                    ),
                    TimeBlockEntity(
                        id = "block-6",
                        startTime = "12:30",
                        endTime = "13:30",
                        blockType = BlockType.MEAL,
                        title = "Bowl Base de Quinoa + Paseo Postprandial",
                        isCompleted = false,
                        sortOrder = 6
                    ),
                    TimeBlockEntity(
                        id = "block-7",
                        startTime = "14:00",
                        endTime = "15:00",
                        blockType = BlockType.MEETING,
                        title = "Alineación Asíncrona / Coordinación de Equipo",
                        isCompleted = false,
                        sortOrder = 7
                    ),
                    TimeBlockEntity(
                        id = "block-8",
                        startTime = "15:30",
                        endTime = "16:30",
                        blockType = BlockType.ADMIN_SLOT,
                        title = "Triaje Administrativo y Tareas Rápidas en Bloque",
                        isCompleted = false,
                        sortOrder = 8
                    ),
                    TimeBlockEntity(
                        id = "block-9",
                        startTime = "22:00",
                        endTime = "23:00",
                        blockType = BlockType.HABIT_ANCHOR,
                        title = "Atardecer Digital & Disociación de Pantallas",
                        isCompleted = false,
                        sortOrder = 9
                    )
                )
                timeBlockDao.insertTimeBlocks(spanishBlocks)

                val spanishPantry = listOf(
                    PantryEntity("p-1", "Huevos Camperos Ecológicos", PantryCategory.PROTEIN, inStock = true, isBatchBase = false, "6 huevos"),
                    PantryEntity("p-2", "Quinoa Tricolor Cocida", PantryCategory.CARB_BASE, inStock = true, isBatchBase = true, "Lote 500g"),
                    PantryEntity("p-3", "Lomo de Salmón Salvaje", PantryCategory.PROTEIN, inStock = true, isBatchBase = false, "2 raciones"),
                    PantryEntity("p-4", "Boniatos Asados al Horno", PantryCategory.CARB_BASE, inStock = true, isBatchBase = true, "3 recipientes"),
                    PantryEntity("p-5", "Espinacas Baby y Rúcula", PantryCategory.PRODUCE, inStock = true, isBatchBase = false, "Bolsa fresca"),
                    PantryEntity("p-6", "Aguacates Maduros", PantryCategory.HEALTHY_FAT, inStock = true, isBatchBase = false, "3 unidades"),
                    PantryEntity("p-7", "Aceite de Oliva Virgen Extra", PantryCategory.HEALTHY_FAT, inStock = true, isBatchBase = false, "Botella llena"),
                    PantryEntity("p-8", "Semillas de Chía y Cáñamo", PantryCategory.HEALTHY_FAT, inStock = true, isBatchBase = false, "1 tarro"),
                    PantryEntity("p-9", "Arándanos Frescos", PantryCategory.PRODUCE, inStock = true, isBatchBase = false, "1 tarrina"),
                    PantryEntity("p-10", "Yogur Griego de Pasto", PantryCategory.PROTEIN, inStock = false, isBatchBase = false, "Por reponer"),
                    PantryEntity("p-11", "Chucrut / Kimchi Fermentado", PantryCategory.PRODUCE, inStock = true, isBatchBase = false, "Medio tarro")
                )
                pantryDao.insertItems(spanishPantry)

                val spanishMeals = listOf(
                    MealEntity(
                        id = "meal-1",
                        slot = MealSlot.BREAKFAST,
                        title = "Revuelto de Huevos Camperos con Aguacate y Arándanos",
                        description = "Desayuno de bajo impacto glucémico que aporta dopamina estable y previene picos de glucosa.",
                        prepTimeMinutes = 10,
                        ingredients = listOf("Huevos Camperos Ecológicos", "Espinacas Baby y Rúcula", "Aguacates Maduros", "Arándanos Frescos"),
                        usesBatchCookedBase = false,
                        allIngredientsInStock = true,
                        bioImpact = BioGlycemicImpact.LOW_GLYCEMIC_FOCUS,
                        isCompleted = true,
                        proteinGrams = 28,
                        carbsGrams = 14,
                        fatGrams = 24,
                        caloriesKcal = 384,
                        dateIso = today
                    ),
                    MealEntity(
                        id = "meal-2",
                        slot = MealSlot.LUNCH,
                        title = "Bowl Energético de Base de Quinoa con Salmón",
                        description = "Aprovecha la base de quinoa precocinada para cocinar en menos de 8 minutos con cero fricción.",
                        prepTimeMinutes = 8,
                        ingredients = listOf("Quinoa Tricolor Cocida", "Lomo de Salmón Salvaje", "Espinacas Baby y Rúcula", "Aceite de Oliva Virgen Extra", "Chucrut / Kimchi Fermentado"),
                        usesBatchCookedBase = true,
                        allIngredientsInStock = true,
                        bioImpact = BioGlycemicImpact.MODERATE_STEADY,
                        isCompleted = false,
                        proteinGrams = 42,
                        carbsGrams = 48,
                        fatGrams = 18,
                        caloriesKcal = 522,
                        dateIso = today
                    ),
                    MealEntity(
                        id = "meal-3",
                        slot = MealSlot.DINNER,
                        title = "Base de Boniato Asado con Hojas Verdes y Grasas Saludables",
                        description = "Recarga de carbohidratos complejos para estimular el sistema nervioso parasimpático y preparar el descanso.",
                        prepTimeMinutes = 12,
                        ingredients = listOf("Boniatos Asados al Horno", "Espinacas Baby y Rúcula", "Aceite de Oliva Virgen Extra", "Semillas de Chía y Cáñamo"),
                        usesBatchCookedBase = true,
                        allIngredientsInStock = true,
                        bioImpact = BioGlycemicImpact.DEEP_RECOVERY,
                        isCompleted = false,
                        proteinGrams = 16,
                        carbsGrams = 62,
                        fatGrams = 14,
                        caloriesKcal = 438,
                        dateIso = today
                    ),
                    MealEntity(
                        id = "meal-4",
                        slot = MealSlot.SNACK,
                        title = "Nueces Crudas e Infusión de Té Matcha",
                        description = "Polifenoles limpios y energía cerebral de liberación progresiva.",
                        prepTimeMinutes = 3,
                        ingredients = listOf("Semillas de Chía y Cáñamo"),
                        usesBatchCookedBase = false,
                        allIngredientsInStock = true,
                        bioImpact = BioGlycemicImpact.LOW_GLYCEMIC_FOCUS,
                        isCompleted = false,
                        proteinGrams = 8,
                        carbsGrams = 6,
                        fatGrams = 18,
                        caloriesKcal = 218,
                        dateIso = today
                    )
                )
                mealDao.insertMeals(spanishMeals)

                val spanishHabits = listOf(
                    HabitAnchor("habit-1", "Ancla Fotónica de Luz Solar Matutina", "10-15 minutos de luz natural directa para calibrar el núcleo supraquiasmático (SCN).", CircadianAnchor.MORNING_LIGHT, true, 12, 1, "Fallar un día es humano; retomar hoy consolida tu línea base."),
                    HabitAnchor("habit-2", "500ml de Agua con Electrolitos Minerales", "Rehidratación celular inmediata al despertar para encender la función ejecutiva.", CircadianAnchor.HYDRATION_ELECTROLYTES, true, 18, 0, "La hidratación celular potencia la claridad mental."),
                    HabitAnchor("habit-3", "Límite de Cafeína a las 14:00 (Depuración de Adenosina)", "Permite la semivida de 8 horas para proteger la fase profunda del sueño.", CircadianAnchor.CAFFEINE_CUTOFF, false, 7, 2, "Protege tu arquitectura de sueño sin culpa."),
                    HabitAnchor("habit-4", "Caminata de Descompresión en Zona 2", "20 minutos de movimiento suave para depurar lactato y reiniciar el foco.", CircadianAnchor.ZONE_2_MOVEMENT, false, 4, 1, "El movimiento rítmico calma el sistema nervioso."),
                    HabitAnchor("habit-5", "Atardecer Digital (Apagar Pantallas a las 22:00)", "Bloqueo de fotones azules para inducir la secreción endógena de melatonina.", CircadianAnchor.DIGITAL_SUNSET, false, 6, 1, "La noche está reservada para la regeneración biológica.")
                )
                habitDao.insertHabits(spanishHabits.map {
                    HabitEntity(
                        id = it.id,
                        title = it.title,
                        description = it.description,
                        anchor = it.anchor,
                        isCompleted = it.isCompleted,
                        streakDays = it.streakDays,
                        graceDaysUsed = it.graceDaysUsed,
                        reframingTip = it.reframingTip
                    )
                })

            } else {
                val englishTasks = listOf(
                    TaskEntity(
                        id = "task-frog-1",
                        title = "Architect Core Engine Logic Specification",
                        description = "Write complete state machine & boundary tests for Aether OS core dispatch module.",
                        energyLevel = EnergyLevel.HIGH,
                        priorityType = PriorityType.FROG,
                        estimatedMinutes = 90,
                        isCompleted = false,
                        isFrog = true,
                        scheduledTime = "09:30 AM",
                        category = "Deep Work"
                    ),
                    TaskEntity(
                        id = "task-med-1",
                        title = "Review Weekly Bio-Analytics & Sleep Trends",
                        description = "Examine heart rate recovery curves and adjust afternoon caffeine window.",
                        energyLevel = EnergyLevel.MEDIUM,
                        priorityType = PriorityType.MEDIUM,
                        estimatedMinutes = 30,
                        isCompleted = false,
                        isFrog = false,
                        scheduledTime = "02:30 PM",
                        category = "Biometrics"
                    ),
                    TaskEntity(
                        id = "task-med-2",
                        title = "Meal Prep: 3-Day Quinoa & Sweet Potato Base",
                        description = "Execute batch cooking protocol to eliminate lunch decision fatigue.",
                        energyLevel = EnergyLevel.MEDIUM,
                        priorityType = PriorityType.MEDIUM,
                        estimatedMinutes = 45,
                        isCompleted = true,
                        isFrog = false,
                        scheduledTime = "05:30 PM",
                        category = "Nutrition"
                    ),
                    TaskEntity(
                        id = "task-med-3",
                        title = "Synthesize Research on Circadian Phase Shifts",
                        description = "Draft concise bullet memo on lux exposure timing for wolf chronotype.",
                        energyLevel = EnergyLevel.MEDIUM,
                        priorityType = PriorityType.MEDIUM,
                        estimatedMinutes = 40,
                        isCompleted = false,
                        isFrog = false,
                        scheduledTime = "11:30 AM",
                        category = "Deep Work"
                    ),
                    TaskEntity(
                        id = "task-quick-1",
                        title = "Clear inbox to Zero / Archive triage",
                        description = "Standard 10m batch processing.",
                        energyLevel = EnergyLevel.LOW,
                        priorityType = PriorityType.QUICK,
                        estimatedMinutes = 15,
                        isCompleted = false,
                        isFrog = false,
                        category = "Admin"
                    ),
                    TaskEntity(
                        id = "task-quick-2",
                        title = "Restock Organic Cold-Pressed Olive Oil",
                        description = "Add to smart pantry list.",
                        energyLevel = EnergyLevel.LOW,
                        priorityType = PriorityType.QUICK,
                        estimatedMinutes = 5,
                        isCompleted = true,
                        isFrog = false,
                        category = "Logistics"
                    ),
                    TaskEntity(
                        id = "task-quick-3",
                        title = "Water balcony herb garden",
                        description = "Sensory micro-break.",
                        energyLevel = EnergyLevel.LOW,
                        priorityType = PriorityType.QUICK,
                        estimatedMinutes = 10,
                        isCompleted = false,
                        isFrog = false,
                        category = "Habit"
                    ),
                    TaskEntity(
                        id = "task-quick-4",
                        title = "Confirm Friday team sprint retro slot",
                        description = "Fast async ping.",
                        energyLevel = EnergyLevel.LOW,
                        priorityType = PriorityType.QUICK,
                        estimatedMinutes = 5,
                        isCompleted = false,
                        isFrog = false,
                        category = "Admin"
                    ),
                    TaskEntity(
                        id = "task-quick-5",
                        title = "Check backup battery levels",
                        description = "Gear maintenance check.",
                        energyLevel = EnergyLevel.LOW,
                        priorityType = PriorityType.QUICK,
                        estimatedMinutes = 5,
                        isCompleted = false,
                        isFrog = false,
                        category = "Logistics"
                    )
                )
                taskDao.insertTasks(englishTasks)

                val englishBlocks = listOf(
                    TimeBlockEntity(
                        id = "block-1",
                        startTime = "07:00",
                        endTime = "08:00",
                        blockType = BlockType.HABIT_ANCHOR,
                        title = "Photonic Anchor & Hydration Charge",
                        isCompleted = true,
                        sortOrder = 1
                    ),
                    TimeBlockEntity(
                        id = "block-2",
                        startTime = "08:00",
                        endTime = "08:45",
                        blockType = BlockType.MEAL,
                        title = "Low-Glycemic Sustained Fuel Breakfast",
                        isCompleted = true,
                        sortOrder = 2
                    ),
                    TimeBlockEntity(
                        id = "block-3",
                        startTime = "09:00",
                        endTime = "10:45",
                        blockType = BlockType.DEEP_WORK,
                        title = "🔥 FROG FOCUS: Core Engine Specification",
                        isCompleted = false,
                        linkedTaskId = "task-frog-1",
                        sortOrder = 3
                    ),
                    TimeBlockEntity(
                        id = "block-4",
                        startTime = "10:45",
                        endTime = "11:15",
                        blockType = BlockType.COGNITIVE_RECOVERY_BUFFER,
                        title = "Active Eye-Rest & Zone 1 Walk",
                        isCompleted = false,
                        sortOrder = 4
                    ),
                    TimeBlockEntity(
                        id = "block-5",
                        startTime = "11:15",
                        endTime = "12:15",
                        blockType = BlockType.DEEP_WORK,
                        title = "Phase Shift Synthesis & Technical Notes",
                        isCompleted = false,
                        linkedTaskId = "task-med-3",
                        sortOrder = 5
                    ),
                    TimeBlockEntity(
                        id = "block-6",
                        startTime = "12:30",
                        endTime = "13:30",
                        blockType = BlockType.MEAL,
                        title = "Batch Base Quinoa Bowl + Digestion Stroll",
                        isCompleted = false,
                        sortOrder = 6
                    ),
                    TimeBlockEntity(
                        id = "block-7",
                        startTime = "14:00",
                        endTime = "15:00",
                        blockType = BlockType.MEETING,
                        title = "Async Sync / Cross-Team Alignment",
                        isCompleted = false,
                        sortOrder = 7
                    ),
                    TimeBlockEntity(
                        id = "block-8",
                        startTime = "15:30",
                        endTime = "16:30",
                        blockType = BlockType.ADMIN_SLOT,
                        title = "Admin Triage & Logistics Batching",
                        isCompleted = false,
                        sortOrder = 8
                    ),
                    TimeBlockEntity(
                        id = "block-9",
                        startTime = "22:00",
                        endTime = "23:00",
                        blockType = BlockType.HABIT_ANCHOR,
                        title = "Digital Sunset & Melatonin Buffer",
                        isCompleted = false,
                        sortOrder = 9
                    )
                )
                timeBlockDao.insertTimeBlocks(englishBlocks)

                val englishPantry = listOf(
                    PantryEntity("p-1", "Organic Eggs", PantryCategory.PROTEIN, inStock = true, isBatchBase = false, "6 eggs"),
                    PantryEntity("p-2", "Cooked Tricolor Quinoa", PantryCategory.CARB_BASE, inStock = true, isBatchBase = true, "500g batch"),
                    PantryEntity("p-3", "Wild Salmon Fillet", PantryCategory.PROTEIN, inStock = true, isBatchBase = false, "2 portions"),
                    PantryEntity("p-4", "Roasted Sweet Potatoes", PantryCategory.CARB_BASE, inStock = true, isBatchBase = true, "3 containers"),
                    PantryEntity("p-5", "Baby Spinach & Arugula", PantryCategory.PRODUCE, inStock = true, isBatchBase = false, "Fresh bag"),
                    PantryEntity("p-6", "Avocados", PantryCategory.HEALTHY_FAT, inStock = true, isBatchBase = false, "3 whole"),
                    PantryEntity("p-7", "Extra Virgin Olive Oil", PantryCategory.HEALTHY_FAT, inStock = true, isBatchBase = false, "Full bottle"),
                    PantryEntity("p-8", "Chia Seeds & Hemp Hearts", PantryCategory.HEALTHY_FAT, inStock = true, isBatchBase = false, "1 jar"),
                    PantryEntity("p-9", "Organic Blueberries", PantryCategory.PRODUCE, inStock = true, isBatchBase = false, "1 box"),
                    PantryEntity("p-10", "Grass-Fed Greek Yogurt", PantryCategory.PROTEIN, inStock = false, isBatchBase = false, "Need restock"),
                    PantryEntity("p-11", "Kimchi / Fermented Slaw", PantryCategory.PRODUCE, inStock = true, isBatchBase = false, "Half jar")
                )
                pantryDao.insertItems(englishPantry)

                val englishMeals = listOf(
                    MealEntity(
                        id = "meal-1",
                        slot = MealSlot.BREAKFAST,
                        title = "Avocado & Pastured Egg Scramble with Blueberries",
                        description = "Low-glycemic breakfast delivering stable dopamine and avoiding glucose spikes.",
                        prepTimeMinutes = 10,
                        ingredients = listOf("Organic Eggs", "Baby Spinach & Arugula", "Avocados", "Organic Blueberries"),
                        usesBatchCookedBase = false,
                        allIngredientsInStock = true,
                        bioImpact = BioGlycemicImpact.LOW_GLYCEMIC_FOCUS,
                        isCompleted = true,
                        proteinGrams = 28,
                        carbsGrams = 14,
                        fatGrams = 24,
                        caloriesKcal = 384,
                        dateIso = today
                    ),
                    MealEntity(
                        id = "meal-2",
                        slot = MealSlot.LUNCH,
                        title = "Batch Base Quinoa Power Bowl with Salmon",
                        description = "Utilizes pre-cooked Tricolor Quinoa base for zero cooking friction.",
                        prepTimeMinutes = 8,
                        ingredients = listOf("Cooked Tricolor Quinoa", "Wild Salmon Fillet", "Baby Spinach & Arugula", "Extra Virgin Olive Oil", "Kimchi / Fermented Slaw"),
                        usesBatchCookedBase = true,
                        allIngredientsInStock = true,
                        bioImpact = BioGlycemicImpact.MODERATE_STEADY,
                        isCompleted = false,
                        proteinGrams = 42,
                        carbsGrams = 48,
                        fatGrams = 18,
                        caloriesKcal = 522,
                        dateIso = today
                    ),
                    MealEntity(
                        id = "meal-3",
                        slot = MealSlot.DINNER,
                        title = "Roasted Sweet Potato Base with Greens & Healthy Fats",
                        description = "Carbohydrate replenishment for parasympathetic nervous system down-regulation.",
                        prepTimeMinutes = 12,
                        ingredients = listOf("Roasted Sweet Potatoes", "Baby Spinach & Arugula", "Extra Virgin Olive Oil", "Chia Seeds & Hemp Hearts"),
                        usesBatchCookedBase = true,
                        allIngredientsInStock = true,
                        bioImpact = BioGlycemicImpact.DEEP_RECOVERY,
                        isCompleted = false,
                        proteinGrams = 16,
                        carbsGrams = 62,
                        fatGrams = 14,
                        caloriesKcal = 438,
                        dateIso = today
                    ),
                    MealEntity(
                        id = "meal-4",
                        slot = MealSlot.SNACK,
                        title = "Handful Walnuts & Green Matcha Infusion",
                        description = "Clean polyphenols and slow release brain fuel.",
                        prepTimeMinutes = 3,
                        ingredients = listOf("Chia Seeds & Hemp Hearts"),
                        usesBatchCookedBase = false,
                        allIngredientsInStock = true,
                        bioImpact = BioGlycemicImpact.LOW_GLYCEMIC_FOCUS,
                        isCompleted = false,
                        proteinGrams = 8,
                        carbsGrams = 6,
                        fatGrams = 18,
                        caloriesKcal = 218,
                        dateIso = today
                    )
                )
                mealDao.insertMeals(englishMeals)

                val englishHabits = listOf(
                    HabitAnchor("habit-1", "Morning Sunlight Photonic Anchor", "10-15 minutes direct outdoor light to reset master circadian clock (SCN).", CircadianAnchor.MORNING_LIGHT, true, 12, 1, "Missing once is human; returning today is your baseline."),
                    HabitAnchor("habit-2", "500ml Water + Mineral Electrolytes", "Rehydrate neural tissue immediately upon waking.", CircadianAnchor.HYDRATION_ELECTROLYTES, true, 18, 0, "Cellular hydration primes executive function."),
                    HabitAnchor("habit-3", "Caffeine Stop at 14:00 (Adenosine Clearance)", "Allows 8h half-life decay to safeguard Stage 3 Deep Sleep.", CircadianAnchor.CAFFEINE_CUTOFF, false, 7, 2, "Protect your sleep architecture without guilt."),
                    HabitAnchor("habit-4", "Zone 2 Decompression Stroll", "20 mins low intensity movement for lactate clearance and cognitive reset.", CircadianAnchor.ZONE_2_MOVEMENT, false, 4, 1, "Movement calms the nervous system."),
                    HabitAnchor("habit-5", "Digital Sunset (Screens Dark at 22:00)", "Suppress blue photons to stimulate natural melatonin synthesis.", CircadianAnchor.DIGITAL_SUNSET, false, 6, 1, "The night belongs to biological rejuvenation.")
                )
                habitDao.insertHabits(englishHabits.map {
                    HabitEntity(
                        id = it.id,
                        title = it.title,
                        description = it.description,
                        anchor = it.anchor,
                        isCompleted = it.isCompleted,
                        streakDays = it.streakDays,
                        graceDaysUsed = it.graceDaysUsed,
                        reframingTip = it.reframingTip
                    )
                })
            }

            // Populate rich historical logs and daily summaries for the past 90 days
            populateDemoHistory(database)
        }

        suspend fun populateDemoHistory(database: AetherDatabase) {
            val completionLogDao = database.completionLogDao()
            val dailySummaryDao = database.dailySummaryDao()

            completionLogDao.clearAllLogs()
            dailySummaryDao.clearAllSummaries()

            val summaries = mutableListOf<DailySummaryEntity>()
            val logs = mutableListOf<CompletionLogEntity>()
            val now = LocalDate.now()

            val sampleHabitTitles = listOf(
                "Luz Solar Matutina (Anclaje Fotónico)",
                "500ml Agua con Electrolitos Minerales",
                "Corte de Cafeína a las 14:00",
                "Caminata de Descompresión Zona 2",
                "Digital Sunset (Pantallas fuera a las 22:00)"
            )
            val sampleTaskTitles = listOf(
                "Arquitectura del Motor Central y Despacho Aether",
                "Revisar Bioanalíticas Semanales y Tendencias de Sueño",
                "Sintetizar Estudio de Cambios de Fase Circadiana",
                "Limpiar bandeja de entrada a Cero (Inbox Zero)",
                "Reponer Aceite de Oliva Virgen Extra Ecológico"
            )

            // Generate past 90 days of rich history with realistic variation (green, amber, slight red)
            for (dayOffset in 90 downTo 0) {
                val date = now.minusDays(dayOffset.toLong())
                val dateIso = date.toString()
                val dayOfWeek = date.dayOfWeek.value // 1..7 (Mon..Sun)

                // Realistic performance pattern: higher on weekdays, slight relaxation on weekends
                val totalCount = if (dayOfWeek in 1..5) 8 else 6
                val completedCount = when {
                    dayOffset == 0 -> 4 // today in progress
                    dayOffset % 17 == 0 -> 2 // rare low day (<30% red)
                    dayOffset % 7 == 0 -> 4 // weekend chill (amber)
                    dayOffset % 5 == 0 -> 5 // amber day
                    else -> if (dayOfWeek in 1..5) 7 else 5 // solid green day (>=70%)
                }
                val partialCount = if (dayOffset % 4 == 0) 1 else 0
                val ratio = ((completedCount.toFloat() + partialCount.toFloat() * 0.5f) / totalCount.toFloat()).coerceIn(0f, 1f)

                summaries.add(
                    DailySummaryEntity(
                        dateIso = dateIso,
                        totalCount = totalCount,
                        completedCount = completedCount,
                        partialCount = partialCount,
                        ratio = ratio
                    )
                )

                // Add 3-5 log entries per day with realistic timestamps
                val baseEpoch = date.atTime(8, 0).atZone(java.time.ZoneId.systemDefault()).toInstant().toEpochMilli()
                
                // Habit logs
                sampleHabitTitles.take(3).forEachIndexed { index, habitTitle ->
                    val status = if (index < completedCount) CompletionStatus.COMPLETED else CompletionStatus.MISSED
                    logs.add(
                        CompletionLogEntity(
                            dateIso = dateIso,
                            itemType = CompletionItemType.HABIT,
                            itemId = "habit-${index + 1}",
                            title = habitTitle,
                            status = status,
                            timestamp = baseEpoch + (index * 3600_000L)
                        )
                    )
                }

                // Task logs
                sampleTaskTitles.take(2).forEachIndexed { index, taskTitle ->
                    val isFrog = index == 0
                    val isComp = (completedCount > index + 2)
                    logs.add(
                        CompletionLogEntity(
                            dateIso = dateIso,
                            itemType = CompletionItemType.TASK,
                            itemId = if (isFrog) "task-frog-1" else "task-med-$index",
                            title = taskTitle,
                            status = if (isComp) CompletionStatus.COMPLETED else CompletionStatus.MISSED,
                            timestamp = baseEpoch + 14400_000L + (index * 7200_000L)
                        )
                    )
                }

                // Meal log
                logs.add(
                    CompletionLogEntity(
                        dateIso = dateIso,
                        itemType = CompletionItemType.MEAL,
                        itemId = "meal-1",
                        title = "Desayuno de Bajo Impacto Glucémico",
                        status = CompletionStatus.COMPLETED,
                        timestamp = baseEpoch + 1800_000L
                    )
                )
            }

            dailySummaryDao.insertSummaries(summaries)
            completionLogDao.insertLogs(logs)
        }
    }
}
